server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: faheem10
    url: jdbc:mysql://localhost:3306/registration
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: faheem
    password: faheem

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000





